# Docker Compose para PostgreSQL
# Alternativa rápida para instalar PostgreSQL

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: paddle_postgres
    environment:
      POSTGRES_DB: paddle_challenge_db
      POSTGRES_USER: paddle_user
      POSTGRES_PASSWORD: paddle123
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: paddle_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@paddle.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: